"""为用户（User）和角色（Role）模型添加创建时间和更新时间字段

Revision ID: 3521fea87a76
Revises: 03f41e9d8c8a
Create Date: 2024-09-25 18:27:25.844202

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '3521fea87a76'
down_revision = '03f41e9d8c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### 首先添加列 ###
    op.add_column('role', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))

    # 为现有记录设置默认值
    op.execute("UPDATE role SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE \"user\" SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL")

    # 将列设置为非空
    op.alter_column('role', 'created_at', nullable=False)
    op.alter_column('role', 'updated_at', nullable=False)
    op.alter_column('user', 'created_at', nullable=False)
    op.alter_column('user', 'updated_at', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('role', 'updated_at')
    op.drop_column('role', 'created_at')
    # ### end Alembic commands ###
