"""迁移接口上报相关功能表

Revision ID: f95813c2b330
Revises: 3521fea87a76
Create Date: 2024-09-27 16:58:40.139438

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f95813c2b330'
down_revision = '3521fea87a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ignore_interface',
    sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_name_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_name', sa.String(), nullable=True, comment='上传名称'),
    sa.Column('eureka_name', sa.String(), nullable=True, comment='Eureka 名称'),
    sa.Column('name', sa.String(), nullable=True, comment='项目名称'),
    sa.Column('description', sa.String(), nullable=True, comment='描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_time', sa.DateTime(), nullable=True, comment='执行时间'),
    sa.Column('action', sa.String(), nullable=True, comment='动作'),
    sa.Column('details', sa.String(), nullable=True, comment='详细信息'),
    sa.Column('name', sa.String(), nullable=True, comment='项目名称'),
    sa.Column('count', sa.Integer(), nullable=True, comment='数量'),
    sa.Column('batch_id', sa.String(), nullable=True, comment='批次号'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_interface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=True, comment='接口路径'),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sa.VARCHAR(), nullable=True, comment='请求方法'),
    sa.Column('description', sa.VARCHAR(), nullable=True, comment='接口描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gather_interface',
    sa.Column('url', sa.VARCHAR(), nullable=True, comment='接口路径'),
    sa.Column('method', sa.VARCHAR(), nullable=True, comment='请求方法'),
    sa.Column('description', sa.VARCHAR(), nullable=True, comment='接口描述'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否已实现自动化'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name_mapping_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_name_mapping_id'], ['project_name_mapping.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gather_interface')
    op.drop_table('upload_interface')
    op.drop_table('transaction_log')
    op.drop_table('project_name_mapping')
    op.drop_table('ignore_interface')
    # ### end Alembic commands ###
